### ISSUE TITLE
Thread Performance Checker.

### ISSUE THREAD

**Issue by PrLion** [apple/swift-nio#2510] opened 2023-08-23 19:01 UTC
Thread Performance Checker: Thread running at QOS_CLASS_USER_INITIATED waiting on a lower QoS thread running at QOS_CLASS_DEFAULT. Investigate ways to avoid priority inversions

SwiftNIO 2.58.0

**Comment by Lukasa** [comment] 2023-08-23 19:49
This is a dupe of #2223. Please check for duplicate issues before filing. Thanks!

**Closed by Lukasa** 2023-08-23 19:49 UTC
