### ISSUE TITLE
Thread running at QOS_CLASS_USER_INTERACTIVE waiting on a lower QoS thread running at QOS_CLASS_DEFAULT

### ISSUE THREAD

**Issue by dandepeched** [apple/swift-nio#2491] opened 2023-08-06 11:59 UTC
In Xcode 14 I have following error in SwiftNIO pod:
".. /Pods/SwiftNIOPosix/Sources/NIOPosix/MultiThreadedEventLoopGroup.swift:121 Thread running at QOS_CLASS_USER_INTERACTIVE waiting on a lower QoS thread running at QOS_CLASS_DEFAULT."

![Screen Shot 2023-08-06 at 14 57 34 PM](https://github.com/apple/swift-nio/assets/5269832/c195e03e-d3a1-4e32-979f-07daf937aa5a)

I'm not sure where this QOS setting came from, I don't use it in my project. So I suspect this is some correction that needs to be done in Pod itself.

**Comment by Lukasa** [comment] 2023-08-06 14:40
Thanks for filing this. This is a dupe of #2223.

**Closed by Lukasa** 2023-08-06 14:40 UTC

**Comment by 1proprogrammerchant** [comment] 2023-08-06 23:39
skilled
