### ISSUE TITLE
NIO does not compile with library evolution enabled

### ISSUE THREAD

**Issue by swansontec** [apple/swift-nio#2470] opened 2023-07-12 19:12 UTC
### Expected behavior

NIO should compile with library evolution enabled.

### Actual behavior

```
swift-nio/Sources/_NIODataStructures/Heap.swift:33:22: error: 'self' used before 'self.init' call or assignment to 'self'
        self.storage = []
                     ^
swift-nio/Sources/_NIODataStructures/Heap.swift:34:5: error: 'self.init' isn't called on all paths before returning from initializer
    }
    ^
swift-nio/Sources/_NIODataStructures/PriorityQueue.swift:21:20: error: 'self' used before 'self.init' call or assignment to 'self'
        self._heap = Heap()
                   ^
swift-nio/Sources/_NIODataStructures/PriorityQueue.swift:22:5: error: 'self.init' isn't called on all paths before returning from initializer
    }
    ^
```

This happens because the "library evolution" feature places extra restrictions on inline initializers like these, which don't apply to normal Swift code.

### Steps to reproduce

Clone any recent version of swift-nio, then compile as:

```sh
xcodebuild \
  -scheme NIO \
  -destination 'generic/platform=iOS' \
  archive \
  SKIP_INSTALL=NO \
  BUILD_LIBRARY_FOR_DISTRIBUTION=YES
```

The above errors will appear. Removing the `BUILD_LIBRARY_FOR_DISTRIBUTION=YES` flag will allow the build to succeed, but then we don't get a module interface file.

This problem also occurs when NIO is used as a dependency. When I build my own library with `BUILD_LIBRARY_FOR_DISTRIBUTION=YES`, I get the same NIO errors.

### If possible, minimal yet complete reproducer code (or URL to code)

See above.

### SwiftNIO version/commit hash

2.56.0

### System & version information

macOS 13.4.1
Xcode 14.3.1
Apple Swift version 5.8.1

**Comment by Lukasa** [comment] 2023-07-12 19:31
Dupe of #1257.

**Closed by Lukasa** 2023-07-12 19:31 UTC
