### ISSUE TITLE
Cannot compile Swift NIO with static Linux SDK on macOS (missing required module '_FoundationCollections')

### ISSUE THREAD

**Issue by leinelissen** [apple/swift-nio#2886] opened 2024-09-17 20:31 UTC
### Expected behavior
I wanted to try out the new static Linux SDK with an app I'm writing in Vapor, but it fails to compile.

### Actual behavior
The executable fails to build with these repeating errors: 
```
<unknown>:0: warning: libc not found for 'x86_64-swift-linux-musl'; C stdlib may be unavailable
<unknown>:0: error: missing required module '_FoundationCollections'
```

[verbose-build-log.txt](https://github.com/user-attachments/files/17034607/verbose-build-log.txt)

### Steps to reproduce
I've followed the instructions on the Swift website: https://www.swift.org/documentation/articles/static-linux-getting-started.html. 

1. Install the 6.0 Swift Toolchain
2. Install the Static Linux SDK:
```
swift sdk install https://download.swift.org/swift-6.0-release/static-sdk/swift-6.0-RELEASE/swift-6.0-RELEASE_static-linux-0.0.1.artifactbundle.tar.gz --checksum 7984c2cf175bde52ba6ea1fcbe27fc4a148a6237c41c719209c9288ed3ceb652
```
3. `swift package init --type executable`
4. Add `swift-nio` to `Package.swift`:
```swift
import PackageDescription

let package = Package(
    name: "swift-hello-world",
    dependencies: [
        .package(url: "https://github.com/apple/swift-nio", from: "2.0.0")
    ],
    targets: [
        // Targets are the basic building blocks of a package, defining a module or a test suite.
        // Targets can depend on other targets in this package and products from dependencies.
        .executableTarget(
            name: "swift-hello-world",
            dependencies: [
                .product(name: "NIOCore", package: "swift-nio"),
                .product(name: "NIOPosix", package: "swift-nio"),
            ]
        )
    ]
)

```
5. Attempt to build static binary:
```
swift build --swift-sdk x86_64-swift-linux-musl
```

### SwiftNIO version/commit hash

Tested with `v2.72.0`

### System & version information

macOS Sonoma 14.6.1, M2 Max, Swift 6.0

I've done some preliminary analysis, and found that the error pops up with the `NIOPosix` module (among others). `_FoundationCollections` is supplied by `swift-collections`, but the error does not appear when only building that particular package. I have tried to figure out how they interlock, and I might be opening an issue in the wrong repository, but please point me in right direction if so.

I've also looked if there are any missing `import Musl` statements next to `import Glibc` statements, but that looks good as far as I can tell.

**Comment by Lukasa** [comment] 2024-09-18 07:52
Thanks for this! I’m closing this as a dupe of apple/swift-collections#420. This tracks the underlying issue in Collections.

**Closed by Lukasa** 2024-09-18 07:52 UTC
