### ISSUE TITLE
Consider allowing call to NIOThreadPool.start() while pool is already running

### ISSUE THREAD

**Issue by kmahar** [apple/swift-nio#1307] opened 2019-12-16 22:28 UTC
### Expected behavior
Based on the docstring for `NIOThreadPool.start` ("Start the `NIOThreadPool` if not already started"), and that calling shutdown multiple times is shown to be safe in the tests, I assumed a repeated call to `start` would also be safe/a no-op. 

### Actual behavior
The assertion [here](https://github.com/apple/swift-nio/blob/c1f05449807578374cd12465d652c10a27a90184/Sources/NIO/NIOThreadPool.swift#L171) is triggered.

My use case is that I'd like to lazily start the thread pool the first time I use it without having to track whether I already called `start`.

This seems like a pretty small code change, or alternatively, a small documentation change to clarify repeated calls to this method are unsafe, and I'd be happy to make a PR either way.

### Steps to reproduce
Call `start` twice.

### If possible, minimal yet complete reproducer code (or URL to code)
```swift
let threadPool = NIOThreadPool(numberOfThreads: 1)
threadPool.start()
threadPool.start() // triggers assertion
```

### SwiftNIO version/commit hash

2.11.1

### Swift & OS version (output of `swift --version && uname -a`)
Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)
Target: x86_64-apple-darwin18.7.0
Darwin kaitlin.fios-router.home 18.7.0 Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64 x86_64

**Comment by weissi** [comment] 2019-12-16 23:58
Thanks for the bug report @kmahar . Definitely either the docs or the code are wrong ☺️.

I’m not sure which to fix right now. Allowing double-start would come with extra questions such as what to do with a start when it comes whilst a shutdown is ongoing. Currently, we fatalError there, but should we ignore that too?

Usually, I’d say start and shutdown calls should be balanced but it would be really easy to just ignore a double start, so we could do that too...

Opinions @Lukasa , @glbrntt , @Davidde94 ?

**Comment by Davidde94** [comment] 2019-12-17 00:05
I agree that balanced start/shutdown calls is nicer, however we should be probably first update the code to be inline with the expected behaviour from the docs. If/when this is done we could push a new release (with new docs) that enforce 1:1 start/shutdown.

**Comment by Lukasa** [comment] 2019-12-17 08:26
I’m inclined to say that either we should require that `start` be called only once, or allow unbalanced and arbitrary numbers of calls. Either of these two cases is easy to tolerate in code, but the in-between case (“balanced but arbitrary count”) is a bit more awkward.

**Comment by glbrntt** [comment] 2019-12-17 14:14
For the actual use case in question, couldn't we just introduce an "auto start" mode? (Such that it would then be like MTELG.)

If so then I _think_ I'd lean towards requiring that `start` is only called once.

**Comment by weissi** [comment] 2019-12-17 14:16
Seems like the consensus (which incidentally aligns with other uses in NIO) is to make it very strict and require exactly one `start` followed by exactly one `stop`.

**Comment by kmahar** [comment] 2019-12-20 17:57
Thank you all for getting back to me! Requiring one start + one stop seems reasonable. 

I've also realized that lazily starting it isn't actually a good idea for what I'm doing anyway so as of now I have no need for an auto-start feature.

**Comment by FranzBusch** [comment] 2021-12-23 09:54
Closing this issue now since we are allowing to call `start()` multiple times. This was fixed with https://github.com/apple/swift-nio/pull/1572

**Closed by FranzBusch** 2021-12-23 09:54 UTC
