### ISSUE TITLE
flaky test: testInstantTCPConnectionResetThrowsError

### ISSUE THREAD

**Issue by PeterAdams-A** [apple/swift-nio#1564] opened 2020-06-19 07:29 UTC
```
2020-06-18 22:05:02.976 - Test Case '-[NIOTests.SocketChannelTest testInstantTCPConnectionResetThrowsError]' started.
2020-06-18 22:05:02.976 - /otmp/od.vhIdCI/lw.h6mPQx/9ka8-suvd91os41nv9_5-1769105/t.AcZ0mE/0~n3JpoGOFvqfO1CTPlpuJ8NgtPzJP-PHYZk9BILebhGj8RJQJ-DsAggEXLw1MI2XaZ3LO6mQ0r2y9uMHijSRyFA==/SRCROOT/Tests/NIOTests/SocketChannelTest.swift:564: error: -[NIOTests.SocketChannelTest testInstantTCPConnectionResetThrowsError] : failed - Should not accept a Channel but got SocketChannel { BaseSocket { fd=11 }, active = false, localAddress = Optional([IPv4]127.0.0.1/127.0.0.1:59692), remoteAddress = Optional([IPv4]127.0.0.1/127.0.0.1:59693) }
2020-06-18 22:05:02.976 - /otmp/od.vhIdCI/lw.h6mPQx/9ka8-suvd91os41nv9_5-1769105/t.AcZ0mE/0~n3JpoGOFvqfO1CTPlpuJ8NgtPzJP-PHYZk9BILebhGj8RJQJ-DsAggEXLw1MI2XaZ3LO6mQ0r2y9uMHijSRyFA==/SRCROOT/Tests/NIOTests/TestUtils.swift:597: error: -[NIOTests.SocketChannelTest testInstantTCPConnectionResetThrowsError] : failed - unexpected error inappropriateOperationForState thrown
2020-06-18 22:05:02.976 - <unknown>:0: error: -[NIOTests.SocketChannelTest testInstantTCPConnectionResetThrowsError] : failed: caught error: "The operation couldn’t be completed. (NIO.ChannelError error 15.)"
2020-06-18 22:05:02.976 - Test Case '-[NIOTests.SocketChannelTest testInstantTCPConnectionResetThrowsError]' failed (0.066 seconds).
```

**Comment by weissi** [comment] 2020-06-22 11:09
```
failed - Should not accept a Channel but got SocketChannel { BaseSocket { fd=11 }, active = false, localAddress = Optional([IPv4]127.0.0.1/127.0.0.1:59692), remoteAddress = Optional([IPv4]127.0.0.1/127.0.0.1:59693) }
```

**Comment by weissi** [comment] 2020-06-22 11:09
this is on macOS

**Comment by weissi** [comment] 2021-01-08 17:11
dupe of #1180

**Closed by weissi** 2021-01-08 17:11 UTC
Labels: flaky-test
