### ISSUE TITLE
Could not connect TCP Sever at simulator

### ISSUE THREAD

**Issue by hieunc278** [apple/swift-nio#1623] opened 2020-08-21 23:18 UTC
Expected behavior

Connect to TCP server at simulator with TCP Client successful

Actual behavior

Failed to connect TCP server at simulator with TCP Client.

The error message show as "2020-08-22 05:55:15.948928+0700 iDine[8523:266860] XPC connection interrupted
2020-08-22 05:57:04.736866+0700 iDine[8523:266862] [ServicesDaemonManager] interruptionHandler is called. -[FontServicesDaemonManager connection]_block_invoke"

Client code

                    Button(action: {
                        let client = TCPClient(host: "localhost", port: 9090)
                        do {
                            try client.start()
                        } catch let error {
                            print("Error: \(error.localizedDescription)")
                            client.stop()
                        }
                    }) {
                        HStack {
                    
                            Text("Login")
                                .font(.title)
                        }
                        .padding()
                        .foregroundColor(.white)
                        .background(Color(red: 0/255, green: 89/255, blue: 121/255))
                        .cornerRadius(20)
                    }.padding(.top, 20)

**Comment by Lukasa** [comment] 2020-08-27 14:09
Dupe of apple/swift-nio-transport-services#104

**Closed by Lukasa** 2020-08-27 14:09 UTC
