### ISSUE TITLE
B2MH nil force unwrap

### ISSUE THREAD

**Issue by tanner0101** [apple/swift-nio#902] opened 2019-03-13 18:46 UTC
### Expected behavior

`ByteToMessageHandler` can be removed from the pipeline and re-added later. 

### Actual behavior

Re-adding a B2MH causes a `nil` force unwrap here: https://github.com/apple/swift-nio/blob/master/Sources/NIO/Codec.swift#L467

### Problem code

```swift
// re-add HTTPDecoder since it may consider the connection to be closed
_ = context.pipeline.removeHandler(httpResDecoder)
_ = context.pipeline.addHandler(httpResDecoder, position: .after(httpReqEncoder))
```

### Fixed code

```swift
// re-add HTTPDecoder since it may consider the connection to be closed
_ = context.pipeline.removeHandler(httpResDecoder)
let newResDecoder = ByteToMessageHandler(HTTPResponseDecoder())
_ = context.pipeline.addHandler(newResDecoder, position: .after(httpReqEncoder))
```

### Note

I'm not sure if I actually need to be re-adding the `HTTPDecoder` anymore here. I had to do this previously to reset the handler since it was viewing the connection as closed after a successful proxy request. 

### SwiftNIO version/commit hash

`2.0.0-convergence.1`

### Swift & OS version (output of `swift --version && uname -a`)

```
Apple Swift version 5.0 (swiftlang-1001.0.69 clang-1001.0.45.2)
Target: x86_64-apple-darwin18.2.0
Darwin iMac.home 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
```

**Comment by weissi** [comment] 2019-03-13 18:50
@tanner0101 most handlers do really not expect that the same instance is to be re-added to a pipeline. We could support this in B2MH but the problem is that random B2MD implementation really won't expect that I think.

I'm probably +0.0001 on making B2MHs re-addable. What does @Lukasa think?

**Comment by Lukasa** [comment] 2019-03-13 18:55
I’m inclined to not support this for now. I think it’ll surprise B2MD implementers, and doing it wrongly will lead to hilariously difficult to diagnose bugs. To reset a handler, I think it’s sufficient to just add a new one.

**Comment by normanmaurer** [comment] 2019-03-13 18:55
In netty we disallow it for any handler which is not marked as @Sharable . I would do the same here

**Comment by tanner0101** [comment] 2019-03-13 18:56
@weissi @Lukasa makes sense to me. But maybe we could have an assertion / fatalError here that has a more helpful debug message? It wasn't immediately obvious to me that this wasn't allowed or what the problem was.

**Comment by normanmaurer** [comment] 2019-03-13 18:57
In netty we throw if someone tries to add the handler again ... maybe we could do the same here (failing the future)

**Comment by tanner0101** [comment] 2019-03-13 18:59
I think the best we can do is an assertion or fatalError. `handlerAdded` doesn't throw or accept a promise:

```swift
func handlerAdded(context: ChannelHandlerContext)
```

**Comment by normanmaurer** [comment] 2019-03-13 19:01
I am talking about the future that is returned by add ... that said yeah it will be expensive to archive to remember if a handler was re added (we do this with an abstract base class in netty so it’s cheap there)

**Comment by weissi** [comment] 2019-03-14 12:37
better crash message for now ^^

**Closed** 2019-03-14 14:05 UTC
Labels: fix-proposed
