### ISSUE TITLE
Slightly flaky test: [NIOAsyncEmbeddedEventLoopTests testCancelledScheduledTasksDoNotHoldOnToRunClosure]

### ISSUE THREAD

**Issue by Davidde94** [apple/swift-nio#2112] opened 2022-05-13 11:08 UTC
Found via internal tools.

```
Test Suite 'Selected tests' started at 2022-05-13 12:06:11.149Test Suite 'swift-nioPackageTests.xctest' started at 2022-05-13 12:06:11.151Test Suite 'NIOAsyncEmbeddedEventLoopTests' started at 2022-05-13 12:06:11.151Test Case '-[NIOEmbeddedTests.NIOAsyncEmbeddedEventLoopTests testCancelledScheduledTasksDoNotHoldOnToRunClosure]' started./private/tmp/nio-release-validator/0507F459-FAC8-41C9-94B1-A8369FF4B6E7/repos/swift-nio/Tests/NIOEmbeddedTests/AsyncEmbeddedEventLoopTests.swift:503: error: -[NIOEmbeddedTests.NIOAsyncEmbeddedEventLoopTests testCancelledScheduledTasksDoNotHoldOnToRunClosure] : XCTAssertNotNil failedTest Case '-[NIOEmbeddedTests.NIOAsyncEmbeddedEventLoopTests testCancelledScheduledTasksDoNotHoldOnToRunClosure]' failed (0.852 seconds).
Test Suite 'NIOAsyncEmbeddedEventLoopTests' failed at 2022-05-13 12:06:12.004.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.852 (0.853) seconds
Test Suite 'swift-nioPackageTests.xctest' failed at 2022-05-13 12:06:12.004.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.852 (0.853) secondsTest Suite 'Selected tests' failed at 2022-05-13 12:06:12.004.
	 Executed 1 test, with 1 failure (0 unexpected) in 0.852 (0.855) seconds
Command failed reason=exit, status=1
```

**Comment by Lukasa** [comment] 2022-05-13 14:16
Dupe of #2105.

**Closed by Lukasa** 2022-05-13 14:16 UTC
Labels: flaky-test
