### ISSUE TITLE
Tsan detects data race

### ISSUE THREAD

**Issue by adtrevor** [apple/swift-nio#736] opened 2019-01-06 23:11 UTC
### Expected behavior
There is no apparent reason for a race condition there

### Actual behavior
Tsan detects a data race on HTTPRequest init call stack, my particular example uses Vapor HTTP lib but it the bug seems located at a lower level.

### Steps to reproduce
Analyse with Tsan tool on the release build config

### If possible, minimal yet complete reproducer code (or URL to code)
```swift
import HTTP
let threadLoopGroup = MultiThreadedEventLoopGroup(numberOfThreads: 1)
let client = try HTTPClient.connect(hostname: "httpbin.org", on: threadLoopGroup).wait()
let httpReq = HTTPRequest(method: .GET, url: "/json") // Race condition detected there
let httpRes = try client.send(httpReq).wait()
```

### SwiftNIO version/commit hash
Swift NIO @ 1.12.0 tag

### Swift & OS version (output of `swift --version && uname -a`)

> Apple Swift version 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)
> Target: x86_64-apple-darwin18.0.0
> Darwin my-computer.home 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64

Thank you!

**Comment by Lukasa** [comment] 2019-01-07 06:59
Yup, this is a dupe of #303: sadly, it’s a swift bug.

**Closed by Lukasa** 2019-01-07 06:59 UTC
