### ISSUE TITLE
Compilation error in SocketAddresses.swift

### ISSUE THREAD

**Issue by amraboelela** [apple/swift-nio#2233] opened 2022-08-03 21:31 UTC
.build/checkouts/swift-nio/Sources/NIOCore/SocketAddresses.swift:79:21: error: stored property '_storage' of 'Sendable'-conforming struct 'IPv4Address' has non-sendable type 'Box<(address: sockaddr_in, host: String)>'
        private let _storage: Box<(address: sockaddr_in, host: String)>

### Expected behavior
_[what you expected to happen]_

### Actual behavior
_[what actually happened]_

### Steps to reproduce

1. Use Linux
2. Use latest swift-no version 2.41.0

### If possible, minimal yet complete reproducer code (or URL to code)

https://github.com/amraboelela/darkeye

### SwiftNIO version/commit hash

ece5057615d1bee848341eceafdf04ca54d60177

### System & version information

Please provide at the very least your operating system and Swift version
information.

Swift version 5.5.1

Ideally, run

```
scripts/nio-diagnose -o nio-diagnose.md PID_OF_YOUR_NIO_PROGRAM
```

and attach (or paste) the resulting file `nio-diagnose.md` into this bug report
or send it to the SwiftNIO maintainers privately.

**Comment by dnadoba** [comment] 2022-08-03 23:40
Hi @amraboelela, thank you for your bug report. 
I could reproduce the issue myself with Swift 5.5.1. The problem is apparently that tuples in Swift 5.5.1 do not conform to Sendable if all Elements of the tuple conform to Sendable (https://github.com/apple/swift/issues/57346). We need to put a couple of @unchecked `Sendable`s on three types: `IPv4Address`, `IPv6Address` and `HTTPHeaders` as they all make use of Tuples as their internal storage. I will work on complete patch tomorrow.
In the meantime you can just update to Swift 5.5.2 or newer which works just fine.

**Comment by dnadoba** [comment] 2022-08-04 10:04
Fixed in https://github.com/apple/swift-nio/pull/2234 and [release in `2.41.1`](https://github.com/apple/swift-nio/releases/tag/2.41.1)

**Closed by dnadoba** 2022-08-04 10:04 UTC

**Comment by cdf1982** [comment] 2023-05-05 11:53
I'm seeing the issue again with the following setup:
- swift-nio.git resolved at 2.50.0
- swift-5.5.1-RELEASE
- Ubuntu 18.04.5 LTS
It's very possible I'm doing something wrong, but the same project compiles with no issue on macOS.

**Comment by Lukasa** [comment] 2023-05-05 12:08
Are you able to update to a newer Swift? We've dropped Swift 5.5 support as of 2.51.0, and it'd be useful to see if a newer compiler resolves the issue.

**Comment by cdf1982** [comment] 2023-05-05 13:26
Thank you for your reply, @Lukasa!

Sure, I'm going to try right away and report back.

While I update Swift, I've been able to deploy an urgent update I needed with an awful work-around: I forced a maximum previous version for Vapor and some dependencies in my project's Package file, and now it compiles again on Ubuntu with the old Swift 5.5.1:

`
        .package(url: "https://github.com/vapor/vapor.git", "4.0.0"..<"4.55.2"),
        .package(url: "https://github.com/apple/swift-nio.git", "2.33.0"..<"2.39.0"),
        .package(url: "https://github.com/apple/swift-nio-http2.git", "1.13.0"..<"1.20.0"),
        .package(url: "https://github.com/apple/swift-nio-extras.git", "1.0.0"..<"1.13.0"),
        .package(url: "https://github.com/apple/swift-nio-ssl.git", "2.8.0"..<"2.18.0"),
`

**Comment by cdf1982** [comment] 2023-05-05 14:08
I'm happy to report that **updating to Swift 5.8**, as recommended by @Lukasa _(which I want to thank again!)_ allowed me to **successfully compile my project on Ubuntu 18.04 LTS as well**, using the **latest Vapor 4.76.0** and without manually limiting the version number of any dependency. 😁
