### ISSUE TITLE
Hang risk. QoS 

### ISSUE THREAD

**Issue by tsomaev** [apple/swift-nio#2611] opened 2023-12-17 22:14 UTC
I work with gRPC, connected gRPC-swift library version 1.21.0, in the process of work started to receive this notification in Xcode 15.0 (15A240d) 

<img width="321" alt="Снимок экрана 2023-12-18 в 01 11 58" src="https://github.com/apple/swift-nio/assets/28268405/51b0aaa1-318f-4628-800a-2912830e59a9">

<br>
<br>

Installed the library via SPM, target version iOS15 

<img width="295" alt="Снимок экрана 2023-12-18 в 01 12 58" src="https://github.com/apple/swift-nio/assets/28268405/ea6b2c1c-e9cb-4e36-b0d0-2c68e3e0b38f">

**Comment by tsomaev** [comment] 2023-12-17 22:32
<img width="1180" alt="Снимок экрана 2023-12-18 в 01 32 16" src="https://github.com/apple/swift-nio/assets/28268405/5a660f85-1034-4e97-8acb-9606d22d9503">

**Comment by glbrntt** [comment] 2023-12-18 09:33
Closing as duplicate of https://github.com/apple/swift-nio/issues/2223

**Comment by glbrntt** [comment] 2023-12-18 09:33
Closing as duplicate of https://github.com/apple/swift-nio/issues/2223

**Closed by glbrntt** 2023-12-18 09:33 UTC
