### ISSUE TITLE
Links to documentation in README are broken: `NIO` -> `NIOCore`

### ISSUE THREAD

**Issue by sukhrobkhakimov** [apple/swift-nio#2007] opened 2021-12-10 10:32 UTC
Since the `NIOCore` library has been extracted from the `NIO`, the links in README are broken. They are still linked to the old `NIO` path.

### Expected, but not working
https://apple.github.io/swift-nio/docs/current/NIOCore/Protocols/EventLoopGroup.html

### Working, but old
https://apple.github.io/swift-nio/docs/current/NIO/Protocols/EventLoopGroup.html

**Comment by Lukasa** [comment] 2021-12-10 10:52
Thanks for filing this! This is a dupe of #1983.

**Closed by Lukasa** 2021-12-10 10:52 UTC
