### ISSUE TITLE
swift-nio repo takes too long to clone 

### ISSUE THREAD

**Issue by OHeroJ** [apple/swift-nio#1592] opened 2020-07-14 14:35 UTC
swift-nio repo takes too long to clone

**Comment by ktoso** [comment] 2020-07-15 02:27
How long is long?
It very could be a matter of your network, or github specifically.

For reference

> time git clone https://github.com/apple/swift-nio 
> 1.77s user 0.53s system 41% cpu 5.523 total # from japan

Is pretty ok

**Comment by glbrntt** [comment] 2020-07-15 07:56
This is a dupe of #1528 -- the `gh-pages` branch is quite large which causes _some_ slowness.

**Comment by ktoso** [comment] 2020-07-15 08:04
Ah the docs, makes sense :) +1ing that ticket

**Closed** 2020-07-15 08:05 UTC
Labels: duplicate

**Comment by OHeroJ** [comment] 2020-07-29 14:09
More than 5 minutes
