### ISSUE TITLE
HTTPDecoder may crash if added to multiple channels, deliberately or not.

### ISSUE THREAD

**Issue by carumusan** [apple/swift-nio#506] opened 2018-07-07 14:29 UTC
### Expected behavior

Not to produce an EXC_BAD_ACCESS

### Actual behavior

```
NIO-ELT-#0 (2): EXC_BAD_ACCESS (code=1, address=0x20)

#0	0x0000000102cbf49e in swift_unknownRetain ()
#1	0x0000000101f8574a in evacuateChannelHandlerContext(_:) at swift-nio.git-6334843834720069654/Sources/NIOHTTP1/HTTPDecoder.swift:698
#2	0x0000000101f83a72 in evacuateHTTPDecoder(_:) at swift-nio.git-6334843834720069654/Sources/NIOHTTP1/HTTPDecoder.swift:702
#3	0x0000000101f8385b in closure #1 in HTTPDecoder.decoderAdded(ctx:) at swift-nio.git-6334843834720069654/Sources/NIOHTTP1/HTTPDecoder.swift:291
#4	0x0000000101f83b11 in @objc closure #1 in HTTPDecoder.decoderAdded(ctx:) ()
#5	0x0000000102090792 in c_nio_http_parser_execute at swift-nio.git-6334843834720069654/Sources/CNIOHTTPParser/c_nio_http_parser.c:777
#6	0x0000000101f8a49d in closure #1 in closure #1 in HTTPDecoder.decodeHTTP(ctx:) at swift-nio.git-6334843834720069654/Sources/NIOHTTP1/HTTPDecoder.swift:487
#7	0x0000000101f94a97 in partial apply for closure #1 in closure #1 in HTTPDecoder.decodeHTTP(ctx:) ()
#8	0x0000000101f8a5a6 in thunk for @callee_guaranteed (@unowned UnsafePointer<Int8>) -> (@unowned Int, @error @owned Error) ()
#9	0x0000000101f94b5a in partial apply for thunk for @callee_guaranteed (@unowned UnsafePointer<Int8>) -> (@unowned Int, @error @owned Error) ()
#10	0x0000000102a184df in UnsafePointer.withMemoryRebound<A, B>(to:capacity:_:) ()
#11	0x0000000101f89dcd in closure #1 in HTTPDecoder.decodeHTTP(ctx:) at swift-nio.git-6334843834720069654/Sources/NIOHTTP1/HTTPDecoder.swift:486
#12	0x0000000101f94891 in partial apply for closure #1 in HTTPDecoder.decodeHTTP(ctx:) ()
#13	0x0000000101f8a6ae in thunk for @callee_guaranteed (@unowned UnsafeRawBufferPointer) -> (@unowned Int, @error @owned Error) ()
#14	0x0000000101f94952 in partial apply for thunk for @callee_guaranteed (@unowned UnsafeRawBufferPointer) -> (@unowned Int, @error @owned Error) ()
#15	0x00000001024db535 in ByteBuffer.withVeryUnsafeBytes<A>(_:) at swift-nio.git-6334843834720069654/Sources/NIO/ByteBuffer-core.swift:493
#16	0x0000000101f7c4a8 in HTTPDecoder.decodeHTTP(ctx:) at swift-nio.git-6334843834720069654/Sources/NIOHTTP1/HTTPDecoder.swift:481
#17	0x0000000101f7f1b3 in HTTPDecoder.channelRead(ctx:data:) at swift-nio.git-6334843834720069654/Sources/NIOHTTP1/HTTPDecoder.swift:595
#18	0x0000000101f8e0f9 in protocol witness for _ChannelInboundHandler.channelRead(ctx:data:) in conformance HTTPDecoder<A> ()
#19	0x0000000102519a5d in ChannelHandlerContext.invokeChannelRead(_:) at swift-nio.git-6334843834720069654/Sources/NIO/ChannelPipeline.swift:1284
#20	0x0000000102519b0f in ChannelHandlerContext.invokeChannelRead(_:) at swift-nio.git-6334843834720069654/Sources/NIO/ChannelPipeline.swift:1286
#21	0x0000000102521702 in ChannelHandlerContext.fireChannelRead(_:) at swift-nio.git-6334843834720069654/Sources/NIO/ChannelPipeline.swift:1097
#22	0x0000000102145b35 in OpenSSLHandler.doDecodeData(ctx:) at swift-nio-ssl.git--7338283827192981615/Sources/NIOOpenSSL/OpenSSLHandler.swift:259
#23	0x0000000102142cd7 in OpenSSLHandler.channelRead(ctx:data:) at swift-nio-ssl.git--7338283827192981615/Sources/NIOOpenSSL/OpenSSLHandler.swift:106
#24	0x00000001021472e9 in protocol witness for _ChannelInboundHandler.channelRead(ctx:data:) in conformance OpenSSLHandler ()
#25	0x0000000102519a5d in ChannelHandlerContext.invokeChannelRead(_:) at swift-nio.git-6334843834720069654/Sources/NIO/ChannelPipeline.swift:1284
#26	0x0000000102510d63 in ChannelPipeline.fireChannelRead0(_:) at swift-nio.git-6334843834720069654/Sources/NIO/ChannelPipeline.swift:808
#27	0x000000010260f0e5 in SocketChannel.readFromSocket() at swift-nio.git-6334843834720069654/Sources/NIO/SocketChannel.swift:144
#28	0x00000001024a178a in BaseSocketChannel.readable0() at swift-nio.git-6334843834720069654/Sources/NIO/BaseSocketChannel.swift:953
#29	0x00000001024a3766 in BaseSocketChannel.readable() at swift-nio.git-6334843834720069654/Sources/NIO/BaseSocketChannel.swift:937
#30	0x00000001024a6160 in protocol witness for SelectableChannel.readable() in conformance BaseSocketChannel<A> ()
#31	0x00000001025502e9 in SelectableEventLoop.handleEvent<A>(_:channel:) at swift-nio.git-6334843834720069654/Sources/NIO/EventLoop.swift:454
#32	0x0000000102551f4a in closure #1 in closure #1 in SelectableEventLoop.run() at swift-nio.git-6334843834720069654/Sources/NIO/EventLoop.swift:503
#33	0x0000000102560099 in partial apply for closure #1 in closure #1 in SelectableEventLoop.run() ()
#34	0x0000000102552089 in thunk for @callee_guaranteed (@guaranteed SelectorEvent<NIORegistration>) -> (@error @owned Error) ()
#35	0x0000000102560142 in partial apply for thunk for @callee_guaranteed (@guaranteed SelectorEvent<NIORegistration>) -> (@error @owned Error) ()
#36	0x00000001025ed23f in Selector.whenReady(strategy:_:) at swift-nio.git-6334843834720069654/Sources/NIO/Selector.swift:590
#37	0x0000000102551b32 in closure #1 in SelectableEventLoop.run() at swift-nio.git-6334843834720069654/Sources/NIO/EventLoop.swift:498
#38	0x0000000102551ca7 in partial apply for closure #1 in SelectableEventLoop.run() ()
#39	0x00000001024911a7 in thunk for @callee_guaranteed () -> (@error @owned Error) ()
#40	0x0000000102551d5f in thunk for @callee_guaranteed () -> (@error @owned Error)partial apply ()
#41	0x000000010254a269 in closure #1 in withAutoReleasePool<A>(_:) at swift-nio.git-6334843834720069654/Sources/NIO/EventLoop.swift:268
#42	0x000000010255fffa in partial apply for closure #1 in withAutoReleasePool<A>(_:) ()
#43	0x00000001033c0f3f in autoreleasepool<A>(invoking:) ()
#44	0x000000010254a14b in withAutoReleasePool<A>(_:) at swift-nio.git-6334843834720069654/Sources/NIO/EventLoop.swift:267
#45	0x0000000102550bd6 in SelectableEventLoop.run() at swift-nio.git-6334843834720069654/Sources/NIO/EventLoop.swift:497
#46	0x0000000102557303 in closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:initializer:) at swift-nio.git-6334843834720069654/Sources/NIO/EventLoop.swift:687
#47	0x000000010255f5da in partial apply for closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:initializer:) ()
#48	0x0000000102557cfc in thunk for @escaping @callee_guaranteed (@guaranteed Thread) -> () ()
#49	0x0000000102632489 in partial apply for thunk for @escaping @callee_guaranteed (@guaranteed Thread) -> () ()
#50	0x0000000102632e45 in closure #1 in static Thread.spawnAndRun(name:body:) at swift-nio.git-6334843834720069654/Sources/NIO/Thread.swift:105

```
### Steps to reproduce

Buffer contents:

(lldb) po bufferSlice.readString(length: 166)
▿ Optional<String>
  - some : "HTTP/1.1 101 Switching Protocols\r\nDate: Sat, 07 Jul 2018 14:07:41 GMT\r\nConnection: upgrade\r\nSec-WebSocket-Accept: KXCK+WbSaeoIR4K6RxA2LEFBiwQ=\r\nUpgrade: WebSocket\r\n\r\n"

Occurs when receiving a websocket upgrade response. Using vapor HTTP and WebSocket repos which uses HTTPResponseDecoder and WebSocketFrameDecoder channel handlers.

### SwiftNIO version/commit hash

Swift NIO 1.8.0

### Swift & OS version (output of `swift --version && uname -a`)

macOS Mojave, Xcode 10 beta 3, Swift 4.2

**Comment by Lukasa** [comment] 2018-07-07 18:31
Can you run your code with Thread Sanitizer turned on and print the results? I’m inclined to believe there is a thread safety problem here.

**Comment by carumusan** [comment] 2018-07-07 19:42
Nothing apparent after turning on Thread Sanitizer or enabling zombie objects. I'm calling HTTPClient.websocket here: [WebSocket+Client.swift](https://github.com/vapor/websocket/blob/master/Sources/WebSocket/WebSocket%2BClient.swift) which in turn calls [HTTPClientProtocolUpgrader.swift](https://github.com/vapor/http/blob/master/Sources/HTTP/Responder/HTTPClientProtocolUpgrader.swift)

**Comment by carumusan** [comment] 2018-07-08 00:43
Sample SwiftPM project: https://github.com/carumusan/swift-nio-exc-error. Compiled with latest XCode beta and macOS mojave it errors on the upgrade response for me.

**Comment by Lukasa** [comment] 2018-07-08 10:21
Cool, so I can reproduce this. Not 100% of the time, but if I run the binary a few times it definitely reproduces.

The crash is odd. It's coming in `swift_unknownRetain` called from `evacuateChannelHandlerContext`. Historically we've seen some crashes here that are to do with seeing excess data delivered to the HTTP parser, but this does not appear to be the issue here, not least because we've landed a number of patches to prevent this from happening.

Normally I'd assume this is because we're attempting to unwrap our pointer to the `ChannelHandlerContext` and its bad. However, the pointer itself is fine. The code is here:

https://github.com/apple/swift-nio/blob/bf1036687b5e6083a518607ad1991a05bd3e567f/Sources/NIOHTTP1/HTTPDecoder.swift#L697-L699

The value of OpaqueContext is `0x00006130000088d8`, and that points to a perfectly reasonable looking parser data structure. On that parser we have a `data` field which should contain a pointer to our hidden `ChannelHandlerContext`. That pointer is set to `0x000060800000db20`, which is basically identical to the value of `ObjectIdentifier(ctx)` from several stack frames up: `0x000060800000d220`. There are a few bytes of offset there which I'm hard-pressed to explain for now, so I may want to try to revisit why that offset is bad, but it's not screamingly, obviously wrong. So for now let's assume that we're passing a valid pointer into `takeUnretainedValue`.

None of these are even close to the address that is *actually* causing the segfault: that's `0x173800040`. Where is that coming from?

Well, here's the assembler corresponding to `swift_unknownRetain`:

```
    0x7fff5a4276a0 <+0>:  testq  %rdi, %rdi
    0x7fff5a4276a3 <+3>:  je     0x7fff5a4276dc            ; <+60>
    0x7fff5a4276a5 <+5>:  movabsq $-0x7fffffffffffffff, %rax ; imm = 0x8000000000000001 
    0x7fff5a4276af <+15>: andq   %rdi, %rax
    0x7fff5a4276b2 <+18>: jne    0x7fff5a4276dc            ; <+60>
    0x7fff5a4276b4 <+20>: movq   0x35869655(%rip), %rax    ; swift_isaMask
    0x7fff5a4276bb <+27>: andq   (%rdi), %rax
->  0x7fff5a4276be <+30>: testb  $0x1, 0x20(%rax)
    0x7fff5a4276c2 <+34>: je     0x7fff5a4276ca            ; <+42>
    0x7fff5a4276c4 <+36>: testb  $0x2, 0x28(%rax)
    0x7fff5a4276c8 <+40>: jne    0x7fff5a4276cf            ; <+47>
    0x7fff5a4276ca <+42>: jmp    0x7fff5a43b2ea            ; symbol stub for: objc_retain
    0x7fff5a4276cf <+47>: pushq  %rbp
    0x7fff5a4276d0 <+48>: movq   %rsp, %rbp
    0x7fff5a4276d3 <+51>: callq  0x7fff5a3e88f0            ; swift_retain
    0x7fff5a4276d8 <+56>: movq   %rax, %rdi
    0x7fff5a4276db <+59>: popq   %rbp
    0x7fff5a4276dc <+60>: movq   %rdi, %rax
    0x7fff5a4276df <+63>: retq   
```

If we look at `rax` we see that it is set to `0x173800020`, which is `0x20` less than our fault address, so pretty clearly this attempt to deference the memory for `testb` is the problem here. So what is in `rax`? Well, `rax` was set two instructions earlier by doing a load of the `swift_isaMask` symbol, and then doing a bitwise `and` of the value at `rdi` with the `swift_isaMask`. What's the value of `rdi` according to my debugger? `0x000060800000db20`, the pointer we're attempting to unwrap. The value at that memory address is `0x173800021` which, when we bitwise AND with the `isaMask` (`0x00007ffffffffff`) gives us `0x173800020`, our bad address.

Let's investigate the possibility we have the wrong address, and that we should be using `0x000060800000d220`. If we do a bitwise AND of the data at *that* address with the `swift_isaMask` we get `0x10299d630`. Adding 20 and dereferencing that pointer does not fault, a good suggestion that somehow we've ended up with the wrong address here.

Running this a few times, it turns out that a great predictor of crashes is when `HTTPDecoder.channelRead` is passed a `ctx` whose `ObjectIdentifier` is different than the value of the pointer in `.data`. Whenever those are different we get a crash, whenever they're the same all is well.

So this suggests we have a memory scribbler. Tracking it down is going to be a bit fussy though, as the corruption is happening *before* we receive a byte of data.

**Comment by Lukasa** [comment] 2018-07-08 10:36
Got it.

**Comment by Lukasa** [comment] 2018-07-08 10:56
So this is a Vapor bug, but it isn't entirely obvious and we really need to add a fix on our end to make doing this a severe error (probably immediately close the channel, maybe just call it a fatal error).

What Vapor is doing is adding the *same* `HTTPDecoder` to multiple channels. The misbehaving function is here:

https://github.com/vapor/http/blob/8123ea00e9858b369cd168d0303d33e7d3804d19/Sources/HTTP/Responder/HTTPClientProtocolUpgrader.swift#L15-L41

The error here is that there are three `ChannelHandler`s created outside of the `.channelInitializer` closure, and passed into that closure by reference. This is not an obvious bug, but because of the way NIO handles HappyEyeballs, each call to `ClientBootstrap.connect` may initialise many channel objects, not just one, and will race them to see which connects first.

This bug manifests whenever the channel that most recently fired `handlerAdded` on the `HTTPDecoder` is not the one that actually connects first. In that situation, the `ChannelHandlerContext` we've stuffed on the `http_parser` object will be freed by the runtime (as we don't increment its refcount), but we won't notice, and we'll attempt to use it and blow up.

The `HTTPDecoder` is not safe to share across multiple `Channel`s, but we can safely police this use, and so we should. Vapor should definitely land a patch, but we should similarly throw errors in this case.

**Comment by Lukasa** [comment] 2018-07-08 11:09
The question is, @jw, is it worth us trying to police this? We'll need to add an `EmbeddedAtomic<Bool>` into our `HTTPDecoder` and use that to track the state. Is it worth it?

**Comment by normanmaurer** [comment] 2018-07-09 08:13
@Lukasa @weissi  in netty we require the user to use an annotation to explicitly mark a `ChannelHandler` as safe to be used multiple times. If this is not provided we fail when the user tries to insert it again. Maybe we should do something similar here ?

**Comment by Lukasa** [comment] 2018-07-09 08:18
What kind of annotation do you have in mind, and how would we implement it? We could use a tag protocol I suppose, but that requires that something external to the handler police this, and I don't know how we could do that.

**Comment by Lukasa** [comment] 2018-07-09 09:54
Just chatted with @weissi.

I'm going to split this into two issues that are more broadly focused than just HTTPDecoder.

**Closed by Lukasa** 2018-07-09 09:54 UTC
Labels: bug
